Table component jose
Lambda-School-Labs/family-promise-service-tracker-fe-a pull request #34
Opened 2021-04-19 21:41 UTC by jcrobles1989

### Description

**What work was done?**

A reusable table component was created, with delete and edit functionality (edit is still being worked on).

**Why was this work done?**

So that data could be rendered in a tabular format and the component used throughout the application. 

**What feature / user story is it for?**
(Link if possible) 

**Any relevant links or images / screenshots**

### Type of change
Please delete options that are not relevant.
[x] New feature (non-breaking change which adds functionality)

Change Status
[] Completed, ready to review and merge
Has This Been Tested
[] Yes

### Checklist
[] My code follows the style guidelines of this project
[x] I have performed a self-review of my own code
[x] My code has been reviewed by at least one peer
[] I have commented my code, particularly in hard-to-understand areas
[x] I have made corresponding changes to the documentation
[] My changes generate no new warnings
[] There are no merge conflicts

2021-04-19 21:46 UTC, princeali415 commented on src/components/common/Table/Table.js
> +];
The user data will be fetched from backend in future but for first run this is good

2021-04-19 21:56 UTC, RubesWorld commented on src/styles/components/_table.less
> +}
Can we convert this to Sass instead of Less?

2021-04-19 22:01 UTC, princeali415 requested changes
Table is good, lets delete the employee page u created and import the table to the main employee page the team has been using so far. We are also using sass not less for styling so talk to ruben about that and he'll help you convert. Overall good work on the table!!

2021-04-20 22:55 UTC, princeali415 approved these changes
Still need to remove .less imports but will merge it now so we can work with the tables

2021-04-20 22:55 UTC, princeali415 commented on src/index.js
>  import './styles/styles.less';
still need to remove this import

2021-04-20 23:05 UTC, merged